#version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
    #KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  -- comando para  criar tópicos automaticamente

    #Cria um tópico chamado sensores com 1 partição e 1 fator de replicação.
    command: >
      bash -c "
      /etc/confluent/docker/run &
      sleep 10 &&
      kafka-topics --create --topic sensores --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 &&
      tail -f /dev/null
      "
      
